Ecdc 3686 pair pixel with tdc and evr calculate tof
ess-dmsc/event-formation-unit pull request #684
Opened 2024-01-24 10:51 UTC by tbukovics

### Issue reference / description

The branch you merge from should already reference an event-formation-unit github ticket number. You can add a descriptive title, but if an issue is referenced, you don't have to.

## Checklist for submitter

- [x] Check for conflict with integration test
- [x] Unit tests pass

---

### Nominate for Group Code Review

- [x] Nominate for code review

2024-01-26 10:30 UTC, mortenjc requested changes

2024-01-26 10:30 UTC, mortenjc commented on src/modules/timepix3/Timepix3Base.h
> +  friend void writePacketToRxFIFO<Timepix3Base>(Timepix3Base &Base, std::vector<uint8_t> Packet);
consider making all members public

2024-01-26 10:30 UTC, mortenjc commented on src/modules/timepix3/Timepix3Instrument.cpp
> +  XTRACE(DATA, DEB, "Processing readouts");
message still correct?

2024-01-26 10:30 UTC, mortenjc commented on src/modules/timepix3/configs/timepix3.json
> +  "NumberOfChunks": 1,
number of partitions?  of the detector surface
add comment?
"comment" : "NumberofChunks - is the fjdkfdjkdjfdkjfd",

2024-01-26 10:30 UTC, mortenjc commented on src/modules/timepix3/dataflow/DataObserverTemplate.h
> +// Copyright (C) 2024 European Spallation Source, see LICENSE file
2023 - 2024

2024-01-26 10:30 UTC, mortenjc commented on src/modules/timepix3/readout/DataParser.cpp
>      if (ReadoutType == 11) {
Add #define or constexpression instead of hardcoded number

2024-01-26 10:30 UTC, mortenjc commented on src/modules/timepix3/readout/DataParser.cpp
> -      if (Data->Type == 15) {
etc. no hardcoded number

2024-01-26 10:30 UTC, mortenjc commented on src/modules/timepix3/readout/DataParser.h
> +#include "Counters.h"
Use <> generally
possibly adding the full path from <modules/...../>

2024-01-26 10:30 UTC, mortenjc commented on src/modules/timepix3/readout/TimepixDataTypes.h
> +#define PIXEL_MAX_TIMESTAMP_NS 26.8435456 * 1e9
constexpr float/double  instead or if an integer
26'000'123'455

2024-01-26 10:30 UTC, mortenjc commented on src/modules/timepix3/readout/TimingEventHandler.cpp
> +// Copyright (C) 2024 European Spallation Source, see LICENSE file
2023-2024

2024-01-26 10:30 UTC, mortenjc commented on src/modules/timepix3/readout/TimingEventHandler.h
> +// Copyright (C) 2024 European Spallation Source, see LICENSE file
2023-2024

2024-01-26 10:30 UTC, mortenjc commented on src/modules/timepix3/readout/TimingEventHandler.h
> +#include "Counters.h"
<>  instead of""

2024-01-26 10:30 UTC, mortenjc commented on src/modules/timepix3/readout/TimingEventHandler.h
> +#define TDC_MAX_TIMESTAMP_NS 107.3741824 * 1e9
check constants (int, float, double)

2024-01-26 10:30 UTC, mortenjc commented on src/modules/timepix3/test/Timepix3ParserTest.cpp
> +
creative formatting :-)

2024-02-05 15:22 UTC, tbukovics reviewed
All requested changes are performed. New unit test are added, coverage is >90%.

2024-02-06 08:11 UTC, mortenjc approved these changes

2024-02-06 08:11 UTC, merged